export default [
  {
    id: 27,
    asunto: "COPIA - 1",
    descripcion: "Prueba prueba prueba",
    tipo: "Proyecto agrupado",
    usuario: "Manavella Edgar Gabriel",
    area: "Adm Insumos",
    sistema: "BI",
    estado: "Pendiente aprobación",
    prioridad: "5",
    importante: "NO",
    col: "target",
  },
  {
    id: 31,
    asunto: "COPIA - 2",
    descripcion: "asas",
    tipo: "Error de sistema",
    usuario: "Manavella Edgar Gabriel",
    area: "Administracion",
    sistema: "Visual Bolsa",
    estado: "Pendiente aprobación",
    prioridad: "5",
    importante: "SI",
    col: "target",
  },
  {
    id: 33,
    asunto: "COPIA - 3",
    descripcion: "dsdsds",
    tipo: "Observación de garantías",
    usuario: "Manavella Edgar Gabriel",
    area: "Adm SGR",
    sistema: "Visual Bolsa",
    estado: "Pendiente aprobación",
    prioridad: "5",
    importante: "SI",
    col: "target",
  },
  {
    id: 34,
    asunto: "COPIA - 4",
    descripcion: "prueba 3 prueba 3 prueba 3 prueba 3 prueba 3 prueba 3",
    tipo: "Pedido de hardware",
    usuario: "Manavella Edgar Gabriel",
    area: "Adm Insumos",
    sistema: "Visual Bolsa",
    estado: "Pendiente aprobación",
    prioridad: "5",
    importante: "SI",
    col: "target",
  },
  {
    id: 37,
    asunto: "COPIA - 5",
    descripcion: "aaa",
    tipo: "Proyecto agrupado",
    usuario: "Manavella Edgar Gabriel",
    area: "Coord Agencias",
    sistema: "BI",
    estado: "Pendiente aprobación",
    prioridad: "5",
    importante: "NO",
    col: "target",
  },
  {
    id: 38,
    asunto: "COPIA - 6",
    descripcion: "adasda",
    tipo: "Pedido de hardware",
    usuario: "Manavella Edgar Gabriel",
    area: "Agencia Rosario",
    sistema: "BI",
    estado: "Pendiente aprobación",
    prioridad: "5",
    importante: "NO",
    col: "target",
  },
]
