export default [
  {
    id: 1,
    asunto: "1",
    descripcion: "Prueba prueba prueba",
    tipo: "Proyecto agrupado",
    usuario: "Manavella Edgar Gabriel",
    area: "Adm Insumos",
    sistema: "BI",
    estado: "Pendiente aprobación",
    prioridad: "5",
    importante: "NO",
    col: "source",
  },
  {
    id: 2,
    asunto: "2",
    descripcion: "asas",
    tipo: "Error de sistema",
    usuario: "Manavella Edgar Gabriel",
    area: "Administracion",
    sistema: "Visual Bolsa",
    estado: "Pendiente aprobación",
    prioridad: "5",
    importante: "SI",
    col: "source",
  },
  {
    id: 3,
    asunto: "3",
    descripcion: "dsdsds",
    tipo: "Observación de garantías",
    usuario: "Manavella Edgar Gabriel",
    area: "Adm SGR",
    sistema: "Visual Bolsa",
    estado: "Pendiente aprobación",
    prioridad: "5",
    importante: "SI",
    col: "source",
  },
  {
    id: 4,
    asunto: "4",
    descripcion: "prueba 3 prueba 3 prueba 3 prueba 3 prueba 3 prueba 3",
    tipo: "Pedido de hardware",
    usuario: "Manavella Edgar Gabriel",
    area: "Adm Insumos",
    sistema: "Visual Bolsa",
    estado: "Pendiente aprobación",
    prioridad: "5",
    importante: "SI",
    col: "source",
  },
  {
    id: 5,
    asunto: "5",
    descripcion: "aaa",
    tipo: "Proyecto agrupado",
    usuario: "Manavella Edgar Gabriel",
    area: "Coord Agencias",
    sistema: "BI",
    estado: "Pendiente aprobación",
    prioridad: "5",
    importante: "NO",
    col: "source",
  },
  {
    id: 6,
    asunto: "6",
    descripcion: "adasda",
    tipo: "Pedido de hardware",
    usuario: "Manavella Edgar Gabriel",
    area: "Agencia Rosario",
    sistema: "BI",
    estado: "Pendiente aprobación",
    prioridad: "5",
    importante: "NO",
    col: "source",
  },
]
