export default [
  {
    id: 27,
    asunto: "Prueba",
    descripcion: "Prueba prueba prueba",
    tipo: "Proyecto agrupado",
    usuario: "Manavella Edgar Gabriel",
    area: "Adm Insumos",
    sistema: "BI",
    estado: "Pendiente aprobación",
    prioridad: "5",
    importante: "NO",
  },
  {
    id: 31,
    asunto: "qasasa",
    descripcion: "asas",
    tipo: "Error de sistema",
    usuario: "Manavella Edgar Gabriel",
    area: "Administracion",
    sistema: "Visual Bolsa",
    estado: "Pendiente aprobación",
    prioridad: "5",
    importante: "SI",
  },
  {
    id: 33,
    asunto: "ssdds",
    descripcion: "dsdsds",
    tipo: "Observación de garantías",
    usuario: "Manavella Edgar Gabriel",
    area: "Adm SGR",
    sistema: "Visual Bolsa",
    estado: "Pendiente aprobación",
    prioridad: "5",
    importante: "SI",
  },
  {
    id: 34,
    asunto: "prueba 3",
    descripcion: "prueba 3 prueba 3 prueba 3 prueba 3 prueba 3 prueba 3",
    tipo: "Pedido de hardware",
    usuario: "Manavella Edgar Gabriel",
    area: "Adm Insumos",
    sistema: "Visual Bolsa",
    estado: "Pendiente aprobación",
    prioridad: "5",
    importante: "SI",
  },
  {
    id: 37,
    asunto: "aaa",
    descripcion: "aaa",
    tipo: "Proyecto agrupado",
    usuario: "Manavella Edgar Gabriel",
    area: "Coord Agencias",
    sistema: "BI",
    estado: "Pendiente aprobación",
    prioridad: "5",
    importante: "NO",
  },
  {
    id: 38,
    asunto: "sasds",
    descripcion: "adasda",
    tipo: "Pedido de hardware",
    usuario: "Manavella Edgar Gabriel",
    area: "Agencia Rosario",
    sistema: "BI",
    estado: "Pendiente aprobación",
    prioridad: "5",
    importante: "NO",
  },
]
